vpc:
  name: prod-vpc
  cidr_block: 10.30.0.0/16
  subnets:
    - name: prod-public-a
      cidr_block: 10.30.1.0/24
      availability_zone: ap-southeast-1a
      type: public
    - name: prod-public-b
      cidr_block: 10.30.2.0/24
      availability_zone: ap-southeast-1b
      type: public
    - name: prod-private-a
      cidr_block: 10.30.101.0/24
      availability_zone: ap-southeast-1a
      type: private
    - name: prod-private-b
      cidr_block: 10.30.102.0/24
      availability_zone: ap-southeast-1b
      type: private
  routes:
    - destination_cidr_block: 0.0.0.0/0
      subnet_type: public
